const fs=require('fs');const{chromium}=require('/Users/samquill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const src=fs.readFileSync('/Users/samquill/Claude work/Dream Street Shuffle - Game Files/Dream Street Shuffle.twee','utf8');const ms=[...src.matchAll(/^:: (.+?)(?:\s+\[([^\]]*)\])?(?:\s+(\{[^\n]+\}))?\s*$/gm)];const bodies={};ms.forEach((m,i)=>bodies[m[1]]=src.slice(m.index+m[0].length,ms[i+1]?.index??src.length));
const base='(set: $metRed to true)(set: $returns to 8)(set: $sawAoifeReflection to true)(set: $sawAoifeMemory2 to true)(set: $hadPhoneCall to true)(set: $hadLilyCall1 to true)(set: $hadDualRing to true)(set: $shownOpenNightTip to true)(set: $shownVenueHint to true)(set: $primerShown to true)(set: $hasMatches to true)(set: $hasCoin to true)(set: $alba to (a: $alba1))(set: $visited\'s French to true)';
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});let results=[];
async function run(name,target,seeds,actions=[]){const p=await b.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({start,header})=>document.addEventListener('DOMContentLoaded',()=>{document.querySelector('tw-passagedata[name="Start"]').textContent=start;document.querySelector('tw-passagedata[name="header header"]').textContent=header;document.querySelector('tw-storydata').setAttribute('startnode',document.querySelector('tw-passagedata[name="Start"]').getAttribute('pid'));}),{start:bodies.Start.replace('(go-to: "The Walk In")',base+seeds+'\n(go-to: '+JSON.stringify(target)+')'),header:bodies['header header']+'\n<div id="audit-name">(print: (passage:)\'s name)</div>\n(link-repeat: "AUDIT READ")[<div id="audit-state">(print: (a: $returns,$metCritic,$inisToldOfPillars,$dreamKey,$alba,$haunts,$metShana,$completedSetlist,$metDavy,$knowsCopperSecret,$sobriety))</div>]'});await p.goto('http://localhost:8732/Dream%20Street%20Shuffle.html',{waitUntil:'domcontentloaded'});await p.waitForTimeout(1200);await p.evaluate(()=>[...document.querySelectorAll('tw-link')].find(e=>e.textContent.trim()==='On.')?.click());await p.waitForTimeout(700);let steps=[];
for(const a of actions){const r=await p.evaluate(txt=>{let es=document.querySelectorAll('tw-link');let e=[...es].find(e=>e.textContent.trim()===txt);if(!e)return false;e.click();return true},a);await p.waitForTimeout(650);steps.push({action:a,found:r,at:await p.locator('#audit-name').last().textContent().catch(()=>'?')});}
await p.evaluate(()=>[...document.querySelectorAll('tw-link')].find(e=>e.textContent==='AUDIT READ')?.click());const out=await p.evaluate(()=>({at:document.querySelector('#audit-name')?.textContent,state:document.querySelector('#audit-state')?.textContent,errors:[...document.querySelectorAll('tw-error')].map(e=>e.textContent),links:[...document.querySelectorAll('tw-link')].map(e=>e.textContent.trim()),doors:[...document.querySelectorAll('.soho-door-label')].map(e=>({text:e.textContent,cls:e.className}))}));results.push({name,steps,...out,jsErrors:errors});console.log(JSON.stringify(results.at(-1)));await p.close();}
await run('Pillars after line 2','Dean Street','(set: $metCritic to true)(set: $tookLily2 to true)(set: $knowsAboutPage to true)(set: $inisToldOfPillars to true)(set: $returnedPage to true)(set: $alba to (a: $alba1,$alba2))(set: $dreamKey to "lighter")(set: $keyLighter to "held")');
await run('Cow ready outside crisis','Dean Street','(set: $metCritic to true)(set: $alba to (a: $alba1,$alba2))(set: $haunts to (a: $haunt3))');
await run('Shana leave before verdict','Shana Reads','(set: $hasTrishaMatchbook to true)', ['← Exit to the street','← Back to Dean Street']);
await run('Ronnie leave before Listen','Bar Canvas Win','(set: $knowsRonnies to true)(set: $tookLily3 to true)', ['← Exit to the street','← Back to Dean Street']);
await run('Davy leave before tip','Davy Merkin','(set: $haunts to (a: $haunt1))', ['← Exit to the street','·','Get a drink']);
await run('Pillars first arrival','Entering The Pillars of Hercules','(set: $hadPhoneCall to false)');
await run('Crisis after alba complete','Dean Street','(set: $sobriety to 0)(set: $alba to (a: $alba1,$alba2,$alba3))(set: $haunts to (a: $haunt1,$haunt2,$haunt3,$haunt4,$haunt5,$haunt6,$haunt7,$haunt8,$haunt9,$haunt10))');
fs.writeFileSync('/tmp/dss-audit-results.json',JSON.stringify(results,null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
