const fs=require('fs');const{chromium}=require('/Users/samquill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const src=fs.readFileSync('/Users/samquill/Claude work/Dream Street Shuffle - Game Files/Dream Street Shuffle.twee','utf8');const ms=[...src.matchAll(/^:: (.+?)(?:\s+\[([^\]]*)\])?(?:\s+(\{[^\n]+\}))?\s*$/gm)];const bodies={};ms.forEach((m,i)=>bodies[m[1]]=src.slice(m.index+m[0].length,ms[i+1]?.index??src.length));
const base='(set: $metRed to true)(set: $returns to 8)(set: $sawAoifeReflection to true)(set: $sawAoifeMemory2 to true)(set: $hadPhoneCall to true)(set: $hadLilyCall1 to true)(set: $hadDualRing to true)(set: $shownOpenNightTip to true)(set: $shownVenueHint to true)(set: $primerShown to true)(set: $hasMatches to true)(set: $hasCoin to true)(set: $alba to (a: $alba1))(set: $visited\'s French to true)';

(async()=>{
const b=await chromium.launch({headless:true,channel:'chrome'}); const records=[];
async function make(target,seeds=''){
 const p=await b.newPage(); const errors=[];p.on('pageerror',e=>errors.push(e.message));p.auditErrors=errors;
 await p.addInitScript(({start,header})=>document.addEventListener('DOMContentLoaded',()=>{
 document.querySelector('tw-passagedata[name="Start"]').textContent=start;
 document.querySelector('tw-passagedata[name="header header"]').textContent=header;
 document.querySelector('tw-storydata').setAttribute('startnode',document.querySelector('tw-passagedata[name="Start"]').getAttribute('pid'));
 }),{start:bodies.Start.replace('(go-to: "The Night Ahead")',base+seeds+'\n(go-to: '+JSON.stringify(target)+')'),header:bodies['header header']+'\n<div id="audit-name">(print: (passage:)\'s name)</div>'});
 await p.goto('http://localhost:8732/Dream%20Street%20Shuffle.html',{waitUntil:'domcontentloaded'});await p.waitForTimeout(1500);return p;
}
async function click(p,t){const found=await p.evaluate(t=>{const el=[...document.querySelectorAll('tw-link')].find(e=>e.textContent.trim()===t);if(el)el.click();return !!el},t);if(!found)throw Error('Missing link '+t);await p.waitForTimeout(900);}
async function record(p,name,data){const errors=await p.locator('tw-error').allTextContents();records.push({name,...data,errors,jsErrors:p.auditErrors});if(errors.length||p.auditErrors.length)throw Error(JSON.stringify(records.at(-1)));}
let p=await make('Dawn','(set: $alba to (a: $alba1,$alba2,$alba3))');await p.locator('#dawn-petal-trigger').scrollIntoViewIfNeeded();await p.waitForTimeout(18000);await p.screenshot({path:'/tmp/dawn-after.png'});console.log(await p.evaluate(()=>({petals:document.querySelectorAll('.dawn-petal').length,errors:[...document.querySelectorAll('tw-error')].map(e=>e.textContent)})));await p.waitForTimeout(22000);await p.screenshot({path:'/tmp/dawn-receded.png'});console.log('storm',await p.evaluate(()=>({canvases:document.querySelectorAll('.dawn-petal-wrap canvas').length,ends:document.querySelectorAll('.dawn-petal-finis').length})));await p.evaluate(()=>document.querySelector('#dawn-petal-trigger').remove());await p.waitForTimeout(300);console.log('cleanup',await p.locator('.dawn-petal-wrap').count());await p.close();p=await make('Dawn');await p.emulateMedia({reducedMotion:'reduce'});await p.setViewportSize({width:390,height:844});await p.locator('#dawn-petal-trigger').scrollIntoViewIfNeeded();await p.waitForTimeout(4000);await p.screenshot({path:'/tmp/dawn-mobile-reduced.png'});console.log('mobile',await p.locator('tw-error').allTextContents(),p.auditErrors);await b.close();})().catch(e=>{console.error(e);process.exit(1)});