const {chromium}=require('/Users/samquill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('assert'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),errors=[],results=[];
async function open(mobile=false){const context=await browser.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3}:{viewport:{width:1100,height:1050}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8789/Dream%20Street%20Shuffle.html#dss-debug-jump=Green%20Sea%20House%20of%20Cards',{waitUntil:'domcontentloaded'});await page.locator('.dss-rules-play').click();await page.waitForTimeout(350);return {page,context};}
async function grabCard(p,i){const g=await p.evaluate(i=>_houseCardsDev.snapshot().geometry[i],i),r=await p.locator('#dss-house-cards canvas').boundingBox();await p.mouse.click(r.x+(g.x+g.tx)/2*r.width/600,r.y+(g.y+g.ty)/2*r.height/430);}
const snap=p=>p.evaluate(()=>_houseCardsDev.snapshot());const preview=p=>p.evaluate(()=>_houseCardsDev.preview());
async function put(p,a){await p.evaluate(a=>{_houseCardsDev.angle(a);_houseCardsDev.place();},a);await p.waitForTimeout(350);}
async function foot(p,g){const r=await p.locator('#dss-house-cards canvas').boundingBox();return {x:r.x+g.x*r.width/600,y:r.y+g.y*r.height/430,scale:r.width/600};}
let {page:p,context:c}=await open(),g=await preview(p),pt=await foot(p,g);
await p.mouse.move(pt.x,pt.y);await p.mouse.down();await p.mouse.move(pt.x+20*pt.scale,pt.y);await p.mouse.up();let s=await snap(p);assert.equal(s.used,0);assert(Math.abs((await preview(p)).x-g.x-20)<.01);const base=s.base;
await p.locator('canvas').last().press('ArrowRight');assert.equal((await snap(p)).base,base);await put(p,70);s=await snap(p);assert.equal(s.cards[0].base,base);assert(Math.abs(s.geometry[0].x-g.x-20)<.01);
// Second card's foot remains where set when its own or its partner's lean changes.
await put(p,70);let before=await snap(p);await grabCard(p,0);await p.locator('#dss-house-cards canvas').press('Shift+ArrowRight');await p.locator('.cards-place').click();await p.waitForTimeout(350);s=await snap(p);assert.equal(s.used,2);assert.equal(s.cards[0].base,before.cards[0].base+2);assert.equal(s.geometry[1].x,before.geometry[1].x);
await grabCard(p,1);await p.getByRole('button',{name:'Base →',exact:true}).click();await p.locator('.cards-place').click();await p.waitForTimeout(350);s=await snap(p);assert.equal(s.cards[1].base,before.cards[1].base+2);assert.equal(s.falls,0);
await grabCard(p,0);await p.evaluate(()=>_houseCardsDev.base(_houseCardsDev.snapshot().base+60));await p.locator('.cards-place').click();assert.equal((await snap(p)).editing,0);assert.equal((await snap(p)).used,2);await p.locator('.cards-cancel').click();s=await snap(p);assert.equal(s.cards[0].base,before.cards[0].base+2);
results.push('mouse foot drag; angle and base independent; shifted placement persists; old-card base edits free; partner foot stays fixed; invalid separation cancels');
// A complete house on shifted foundations, including a shifted upper foot.
while((await snap(p)).active>=0){s=await snap(p);if(s.active===8)await p.evaluate(()=>_houseCardsDev.base(_houseCardsDev.snapshot().base+3));await put(p,s.slots[s.active].kind==='bridge'?0:70);if((await snap(p)).ended)throw Error('Unexpected collapse');}
s=await snap(p);assert.equal(s.standing,15);assert.equal(s.used,15);await p.screenshot({path:__dirname+'/base-desktop.png'});await p.getByRole('button',{name:'Face the roar',exact:true}).click();await p.waitForTimeout(1450);assert.equal(await p.locator('.inventory-note').last().innerText(),'MORALE +12');await p.waitForFunction(()=>!document.querySelector('#dss-house-cards'));assert.equal(await p.locator('tw-error').count(),0);results.push('shifted foundations and upper-storey base complete house, final roar and return');await c.close();
({page:p,context:c}=await open(true));g=await preview(p);pt=await foot(p,g);const cd=await c.newCDPSession(p);
await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:pt.x,y:pt.y}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pt.x+14,y:pt.y}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal((await snap(p)).used,0);assert((await preview(p)).x>g.x+20);await put(p,70);s=await snap(p);const saved=s.cards[0].base;
await grabCard(p,0);g=await preview(p);pt=await foot(p,g);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:pt.x,y:pt.y}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pt.x+9,y:pt.y}]});await cd.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal((await snap(p)).base,saved);assert.equal((await snap(p)).cards[0].base,saved);await p.locator('.cards-cancel').click();
assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:__dirname+'/base-phone.png'});assert.equal(await p.locator('tw-error').count(),0);await p.locator('.cards-skip tw-link').click();await p.waitForFunction(()=>typeof _houseCardsDev==='undefined');results.push('390px touch foot movement, cancel restores base, no overflow, teardown');await c.close();assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/base-results.json',JSON.stringify({results,errors},null,2));console.log(results);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
