const {chromium}=require('/Users/samquill/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert');
(async()=>{
const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),errors=[],results=[];
async function game(mobile=false){const c=await b.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3,reducedMotion:'reduce'}:{viewport:{width:1100,height:1000}});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8789/Dream%20Street%20Shuffle.html#dss-debug-jump=Green%20Sea%20House%20of%20Cards',{waitUntil:'domcontentloaded'});await p.locator('.dss-rules-play').click();await p.waitForTimeout(350);return {p,c};}
async function grabCard(p,i){const g=await p.evaluate(i=>_houseCardsDev.snapshot().geometry[i],i),r=await p.locator('#dss-house-cards canvas').boundingBox();await p.mouse.click(r.x+(g.x+g.tx)/2*r.width/600,r.y+(g.y+g.ty)/2*r.height/430);}
const snap=p=>p.evaluate(()=>_houseCardsDev.snapshot());
async function put(p,a){await p.evaluate(a=>{_houseCardsDev.angle(a);_houseCardsDev.place();},a);await p.waitForTimeout(350);}
async function point(p,i){let s=await snap(p),g=s.geometry[i],r=await p.locator('#dss-house-cards canvas').boundingBox();return {x:r.x+(g.x+g.tx)/2*r.width/600,y:r.y+(g.y+g.ty)/2*r.height/430};}
let {p,c}=await game();await put(p,70);let first=await snap(p);await put(p,70);let second=await snap(p);assert.deepEqual(second.geometry[0],first.geometry[0]);assert.equal(second.cards[0].angle,70);assert(second.nextRoar-second.elapsed>=1.1);
let pt=await point(p,0);await p.mouse.click(pt.x,pt.y);let s=await snap(p);assert.equal(s.editing,0);assert.equal(s.used,2);
await p.locator('#dss-house-cards canvas').press('ArrowRight');await p.locator('#dss-house-cards canvas').press('Space');s=await snap(p);assert.equal(s.cards[0].angle,72);assert.equal(s.used,2);assert.equal(s.editing,-1);
await p.waitForTimeout(350);pt=await point(p,0);await p.mouse.move(pt.x,pt.y);await p.mouse.down();await p.mouse.move(pt.x-13.333,pt.y);await p.mouse.up();s=await snap(p);assert(Math.abs(s.cards[0].angle-68)<.01);assert.equal(s.editing,-1);assert.equal(s.used,2);
await p.waitForTimeout(350);await grabCard(p,0);await p.evaluate(()=>_houseCardsDev.angle(40));await p.locator('.cards-place').click();s=await snap(p);assert.equal(s.editing,0);assert.equal(s.falls,0);assert(Math.abs(s.cards[0].angle-68)<.01);await p.locator('.cards-cancel').click();assert.equal((await snap(p)).editing,-1);
await grabCard(p,0);await p.evaluate(()=>_houseCardsDev.angle(70));await p.locator('.cards-place').click();assert.equal((await snap(p)).cards[0].angle,70);
await p.waitForTimeout(350);s=await snap(p);await p.evaluate(()=>_houseCardsDev.roar());let r=await snap(p);r.cards.forEach((v,i)=>{if(v)assert(Math.abs(v.angle-s.cards[i].angle)<=.81)});results.push('thin cards; placement leaves prior geometry still; tap/keyboard/drag repairs spend no cards; invalid edit safely cancels; gentle tremor');
// Repair after a tremor; the remaining house can still be completed and adjusted.
await grabCard(p,0);await put(p,70);await grabCard(p,1);await put(p,70);
while((await snap(p)).active>=0){s=await snap(p);await put(p,s.slots[s.active].kind==='bridge'?0:70);}
s=await snap(p);assert(s.houseReady);assert.equal(s.finalAt,0);assert.equal(s.used,15);await p.waitForTimeout(1800);assert(!(await snap(p)).ended);
await grabCard(p,6);await put(p,2);s=await snap(p);assert.equal(s.cards[6].angle,2);assert.equal(s.standing,15);assert.equal(s.used,15);
await grabCard(p,6);await put(p,0);await p.screenshot({path:__dirname+'/revision-desktop.png'});
await p.getByRole('button',{name:'Face the roar',exact:true}).click();await p.waitForTimeout(1500);assert.equal(await p.locator('.inventory-note').last().innerText(),'MORALE +12');await p.waitForFunction(()=>!document.querySelector('#dss-house-cards'));assert.equal(await p.locator('tw-error').count(),0);assert.equal(await p.evaluate(()=>typeof _houseCardsDev),'undefined');results.push('completed house waits for final roar; supported bridge adjustable; 15-card completion and distinction return');await c.close();
({p,c}=await game(true));await put(p,70);await put(p,70);pt=await point(p,0);await p.touchscreen.tap(pt.x,pt.y);assert.equal((await snap(p)).editing,0);
let cd=await c.newCDPSession(p);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pt.x+13.333,y:pt.y}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});s=await snap(p);assert(Math.abs(s.cards[0].angle-74)<.01);assert.equal(s.used,2);assert.equal(s.editing,-1);
await p.waitForTimeout(350);pt=await point(p,0);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pt.x+10,y:pt.y}]});await cd.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});s=await snap(p);assert(Math.abs(s.cards[0].angle-74)<.01);assert.equal(s.angle,s.cards[0].angle);await p.locator('.cards-cancel').click();
assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:__dirname+'/revision-phone.png'});assert.equal(await p.locator('tw-error').count(),0);await p.locator('.cards-skip tw-link').click();await p.waitForFunction(()=>!document.querySelector('#dss-house-cards'));assert.equal(await p.evaluate(()=>typeof _houseCardsDev),'undefined');results.push('390px thin-card hit targets; touch selection/drag/cancellation; no horizontal overflow; teardown');await c.close();
assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/revision-results.json',JSON.stringify({results,errors},null,2));console.log(results);await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
